### ISSUE TITLE
The progress thingy doesn’t seem to show the data wasted

### ISSUE THREAD

**Issue by scratchusernamemrtbts** [shivam1608/DataWaster#1]
![5D2C1EDC-D416-4565-AD2F-E8B37D7BD554](https://user-images.githubusercontent.com/66320961/151738596-5117cfb4-530e-44b4-adbc-2ffb573e6b3a.png)
I ran it for a min now and it still have 0 speed and 0 mb wasted

**Comment by shivam1608** [comment]
> ![5D2C1EDC-D416-4565-AD2F-E8B37D7BD554](https://user-images.githubusercontent.com/66320961/151738596-5117cfb4-530e-44b4-adbc-2ffb573e6b3a.png) I ran it for a min now and it still have 0 speed and 0 mb wasted

First of all thank you for creating issue xd its my first issue
Second i looked into the system and saw the server was down from where the waste data comes froml.

In simple words i have fixed the server and now its back into its working state.

**Comment by scratchusernamemrtbts** [comment]
Ok thanks
yea i was wondering why there was no issue
